### ISSUE TITLE
Bug: Executing roku_app_package output the pkg in wrong path.

### ISSUE THREAD

**Issue by rramirez0203** [WarnerMedia/fastlane-plugin-roku_app_util#3]
**Describe the bug**
Executing `roku_app_package`output the pkg in wrong path.

in a project structure like this:
```
.
├── README.md
├── components
│   └── ...
├── fastlane
│   ├── Appfile
│   ├── Fastfile
│   ├── Pluginfile
├── images
│   └── ...
├── manifest
└── source
    └── main.brs
```
the pkg generated is put outside project folder.

**Steps to reproduce**
* Run a lane that internally call `roku_app_package` as described https://github.com/WarnerMedia/fastlane-plugin-roku_app_util/blob/master/fastlane/Fastfile#L19
* Notice how the pkg is put outside project folder

**Expected behavior**
It would be good to pass a param `output_path` that `roku_app_package`use to put the pkg.

**How often does this bug happen?**
Every time

**ruby-version**
ruby 2.6.8p205 (2021-07-07 revision 67951) [arm64-darwin20]

**Comment by onyxmueller** [comment]
Good catch! I was able to duplicate this.

**Comment by onyxmueller** [comment]
Fix merged. Thanks for raising this and your contribution @rramirez0203!
